name: Deploy staging

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    env:
      REACT_APP_ENV: staging
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          echo "ddd"
      - run: echo "🍏 This job's status is ${{ job.status }}."


      - name: Deploy MyApp1
        env:
          REACT_APP: sdfds
        run: |
          echo "sdfdf"

      - name: Deploy MyApp2
        env:
          REACT_APP: dsfds
        run: |
          echo "sdfsdf"

      - name: MyApp3
        env:
          REACT_APP: sdfsdf
        run: |
          echo "sdfds"

      - name: MyApp4
        env:
          REACT_APP: dsfd
        run: |
          echo "sdfd"

      - name: MyApp5
        env:
          REACT_APP: dsfdf
        run: |
          echo "sdfsd"

